#!/usr/bin/env bash
# This bash script configures an Nginx server so that its HTTP response
# contains a custom header
sudo apt-get -y update
sudo apt-get -y install nginx

# insert this line into the config file. HOSTNAME is server name
sudo sed -i "16i\
\\\tadd_header X-Served-By $HOSTNAME;\n" /etc/nginx/nginx.conf

sudo service nginx restart
