#!/usr/bin/env bash
# Install a load balancer
sudo add-apt-repository -y ppa:vbernat/haproxy-1.7
sudo apt -y update
sudo apt -y install haproxy

sudo sed -i "s/ENABLED=0/ENABLED=1/" /etc/default/haproxy

sudo echo -e "
\nfrontend Local_Server
\tbind *:80
\tmode http
\tdefault_ba
backend web-backend
\tmode http
\tbalance roundrobin
\tserver 209-web-01 54.157.250.230
\tserver 209-web-02 107.20.129.42\n
" | sudo tee --append /etc/haproxy/haproxy.cfg

sudo service haproxy restart
