#!/usr/bin/env bash
# This script displays "Holberton School" 10 times except for the 9th time
INDX=0
while [ $INDX -lt 10 ]
do
    if [ $INDX -eq 7 ]
    then
	echo "good luck"
    elif [ $INDX -eq 3 ]
    then
	echo "bad luck"
    else
        echo "Holberton School"
    fi
    INDX=$(( INDX+1 ))
done
