#!/usr/bin/env bash
# This script displays the time
HOUR="0"
while [ $HOUR -lt 13 ]
do
      MIN="1"
      echo "Hour: $HOUR"
      while [ $MIN -lt 60 ]
      do
      	    echo "$MIN"
	    MIN=$(( MIN+=1 ))
      done
      HOUR=$(( HOUR+=1 ))
done
