#!/usr/bin/env bash
# install an nginx web server
# the -y flag will automatically state yes for you since user is not present
#    when the script runs
sudo apt-get -y update
sudo apt-get -y install nginx
# It is much easier to simply echo the phrase into index.html
echo 'Holberton School' > /usr/share/nginx/html/index.html
sudo service nginx restart
